<?php  //[STAMP] f8ac1c8ea3ee07d8889a779d8e42b80c
// phpcs:ignoreFile
namespace Xima\XimaTypo3Recordlist\Tests\Acceptance\Support\_generated;

// This class was automatically generated by build task
// You should not change it manually as it will be overwritten on next build

trait FunctionalTesterActions
{
    /**
     * @return \Codeception\Scenario
     */
    abstract protected function getScenario();

    
}
